# Aprendizaje Automático

## Ángel García Báez

# Introducción 
En el presente reporte se busca poner en funcionamiento los scripts del libro visto en clase _Machine Learning. An Algorithmic Perspective_ en donde se tiene codificado la forma de crear, entrenar y evaluar un perceptrón simple y un perceptrón multicapa.

# Perceptrón Simple

Para el perceptrón simple se tomo de base el algoritmo proporcionado por el repositorio del libro, posteriormente se trato de ejecutar sin ningun exito, puesto que el codigo contaba con una serie de errores cruciales para el correcto funcionamiento del codigo. Los errores que más destacan son: varios comandos _print_ sin parentesis que producian paros en el codigo junto con una versión no dinamica de lo que esperaba el algoritmo recibir para evaluar la matriz de confusión. Dichos problemas fueron solventados para lograr hacer el codigo con normalidad.

A continuación se muestra una pequeña corrida del codigo funcionando con la base de datos de iris, previamente depurada para que contenga unicamente 2 clases (versicolor = 0 y virginica = 1). Cabe mencionar que para hacer funcionar el perceptrón simple, fue necesario escalar los valores de las variables en un rango que va de 0 a 1 para que las predicciones del perceptrón tuvieran sentido.

In [7]:
# Librerias necesarias
import PerceptronS as ps   # Perceptron SIMPLE
import numpy as np # Para manipular arreglos
import pandas as pd # Para manipular arreglos
from sklearn.model_selection import train_test_split # Para dividir en prueba y entrenamiento
from sklearn.preprocessing import StandardScaler # Escalador de las variables
import csv # Para importar datos CSV

In [8]:
#Cargar los datos 
ruta1 =  "C:\\Users\\Angel\\Desktop\\MIA PRIMER SEMESTRE\\Machine Learning\\TAREA 3. PERCEPTRONES\\BASES\\irisvv.csv"
datos = pd.read_csv(ruta1)
datos.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           7.0          3.2           4.7          1.4        0
1           6.4          3.2           4.5          1.5        0
2           6.9          3.1           4.9          1.5        0
3           5.5          2.3           4.0          1.3        0
4           6.5          2.8           4.6          1.5        0

Despues de cargar la base de datos, se toma la base de iris para dividir en conjunto de prueba y conjunto de entrenamiento para poder evaluar que tan bueno es el perceptron simple:

In [9]:
# Dividir manualmente la base
X = datos.iloc[:,:-1].values
Y = datos.iloc[:,-1].values
# Escalar los valores
# Normalizar las características
scaler = StandardScaler()
X = scaler.fit_transform(X)
#Dividir en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=25)
# Convertir y_train a un array bidimensional con una sola columna
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

## Entrenar al perceptrón simple

In [12]:
# 4. Inicializar y entrenar el perceptrón
modeloS = ps.Perceptron(X_train, y_train)  # Redimensionamos y_train para que sea un vector columna
modeloS.pcntrain(X_train, y_train,eta = 0.3,nIterations=100)


Iteration 1, Error: 0.42857142857142855
Iteration 2, Error: 0.6857142857142857
Iteration 3, Error: 0.45714285714285713
Iteration 4, Error: 0.4142857142857143
Iteration 5, Error: 0.4857142857142857
Iteration 6, Error: 0.5
Iteration 7, Error: 0.4857142857142857
Iteration 8, Error: 0.5142857142857142
Iteration 9, Error: 0.44285714285714284
Iteration 10, Error: 0.5428571428571428
Iteration 11, Error: 0.5571428571428572
Iteration 12, Error: 0.4714285714285714
Iteration 13, Error: 0.4857142857142857
Iteration 14, Error: 0.45714285714285713
Iteration 15, Error: 0.5
Iteration 16, Error: 0.42857142857142855
Iteration 17, Error: 0.5571428571428572
Iteration 18, Error: 0.4857142857142857
Iteration 19, Error: 0.6142857142857143
Iteration 20, Error: 0.4714285714285714
Iteration 21, Error: 0.42857142857142855
Iteration 22, Error: 0.44285714285714284
Iteration 23, Error: 0.4
Iteration 24, Error: 0.6
Iteration 25, Error: 0.4142857142857143
Iteration 26, Error: 0.5571428571428572
Iteration 27, Error: 0

## Evaluar al perceptrón simlpe

In [13]:
# 5. Evaluar el modelo en el conjunto de prueba
print("Confusion matrix sobre la data de prueba:")
modeloS.confmat(X_train, y_train)

Confusion matrix sobre la data de prueba:
Confusion Matrix:
[[39  0]
 [ 0 31]]
Accuracy: 1.00


In [14]:
print("\nResultados en conjunto de prueba:")
modeloS.confmat(X_test, y_test)


Resultados en conjunto de prueba:
Confusion Matrix:
[[ 9  0]
 [ 2 19]]
Accuracy: 0.93


# Resultados del perceptron simple
Tras el entrenamiento del perceptron multicapa y de su evaluación, se observa que dicho modelo pese a ser relativamente "simple", dicho modelo logra acertar en un 93.33% de las veces, equivocandose apenas en 2 casos.



# Perceptrón Multicapa

Para correr el perceptrón multicapa, primero fue necesario depurar los errores del codigo. Sorprendentemente, depurar este codigo tomo mucho menos, puesto que unicamente se depuraron los _print_ que no tenian parentesís, despues de esto el codigo funcionaba de forma satisfactoria.


In [15]:
import PerceptronM as pm

In [17]:
# Probar a entrenar la red multicapa con 5 capas ocultas, un eta de 0.2 y 500 iteraciones maximas
modeloM = pm.mlp(X_train, y_train,5)
modeloM.mlptrain(X_train, y_train,0.2,501)

Iteration:  0  Error:  9.376710343784147
Iteration:  100  Error:  0.039566050068154335
Iteration:  200  Error:  0.01702615704479691
Iteration:  300  Error:  0.009531579727847881
Iteration:  400  Error:  0.0062916164028956065
Iteration:  500  Error:  0.004581603251391419


In [18]:
# Hacer la matriz de confusión con los datos de entrenamiento
modeloM.confmat(X_train, y_train)


Confusion matrix is:
[[39.  0.]
 [ 0. 31.]]
Percentage Correct:  100.0


In [20]:
# Hacer la matriz de confusión con los datos de prueba
modeloM.confmat(X_test, y_test)

Confusion matrix is:
[[ 9.  0.]
 [ 2. 19.]]
Percentage Correct:  93.33333333333333


# Resultados del perceptrón multicapa

Tras realizar el ajuste de un modelo de perceptrón multicapa con 5 capas ocultas, se obtuvo una precisión del 93.33%, llegando a los mismos resultados que su versión simple.
